var files_dup =
[
    [ "build", "dir_4fef79e7177ba769987a8da36c892c5f.html", "dir_4fef79e7177ba769987a8da36c892c5f" ],
    [ "acsystem.cpp", "acsystem_8cpp.html", null ],
    [ "acsystem.h", "acsystem_8h.html", "acsystem_8h" ],
    [ "curtains.cpp", "curtains_8cpp.html", null ],
    [ "curtains.h", "curtains_8h.html", "curtains_8h" ],
    [ "device.cpp", "device_8cpp.html", null ],
    [ "device.h", "device_8h.html", "device_8h" ],
    [ "home.cpp", "home_8cpp.html", null ],
    [ "home.h", "home_8h.html", "home_8h" ],
    [ "homemanagement.cpp", "homemanagement_8cpp.html", null ],
    [ "homemanagement.h", "homemanagement_8h.html", "homemanagement_8h" ],
    [ "lights.cpp", "lights_8cpp.html", null ],
    [ "lights.h", "lights_8h.html", "lights_8h" ],
    [ "login.cpp", "login_8cpp.html", null ],
    [ "login.h", "login_8h.html", "login_8h" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "room.cpp", "room_8cpp.html", null ],
    [ "room.h", "room_8h.html", "room_8h" ],
    [ "tv.cpp", "tv_8cpp.html", null ],
    [ "tv.h", "tv_8h.html", "tv_8h" ],
    [ "user.cpp", "user_8cpp.html", null ],
    [ "user.h", "user_8h.html", "user_8h" ],
    [ "usermanagement.cpp", "usermanagement_8cpp.html", null ],
    [ "usermanagement.h", "usermanagement_8h.html", "usermanagement_8h" ],
    [ "usermanagementsystem.cpp", "usermanagementsystem_8cpp.html", null ],
    [ "usermanagementsystem.h", "usermanagementsystem_8h.html", "usermanagementsystem_8h" ]
];